name: BATS Tests

# controls when the action will run.
on:
  # triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jq-version: [ "1.6", "1.7", "1.7.1", "1.8.0", "1.8.1", "latest" ]
      max-parallel: 1

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: setup jq ${{ matrix.jq-version }}
        uses: dcarbone/install-jq-action@v3
        with:
          version: ${{ matrix.jq-version }}
          force: true  # ensure the specified jq version is installed and used

      - name: verify jq version
        run: jq --version

      - name: run unit tests
        run: test/bats/bin/bats --timing test
